language: php
php:
 - '7.3'
 - '7.4'
install:
 - composer install
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
notifications:
  email: false
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
